@startuml


database APIFHIRAnnuaire [
<b>Annuaire</b> FHIR API
]

database APIFHIRROR [
<b>ROR</b> FHIR API
]



artifact "FR Core" as frcore
url of frcore is  [[https://hl7.fr/ig/fhir/core]]

archimate #Technology "Annuaire santé (AnnuaireSante)" as annuaire <<technology-device>>
url of annuaire is  [[https://interop.esante.gouv.fr/ig/fhir/annuaire]]

annuaire --> frcore 
annuaire --> APIFHIRAnnuaire 

artifact "Partage de Docuemnts de Santé en mobilité (PDSm)" as pdsm
url of pdsm is  [[https://interop.esante.gouv.fr/ig/fhir/pdsm]]

pdsm --> frcore 
pdsm --> annuaire


artifact "Mesures de santé (mesures)" as mesures
url of mesures is  [[https://interop.esante.gouv.fr/ig/fhir/mesures]]

mesures --> frcore 


artifact "Suivi Décisions Orientation (SDO)" as sdo
url of sdo is  [[https://interop.esante.gouv.fr/ig/fhir/sdo]]


artifact "Gestion d'Agendas Partagés (GAP)" as gap
url of gap is  [[https://interop.esante.gouv.fr/ig/fhir/gap]]

gap --> frcore 
gap --> annuaire


' artifact "Cercle De Soins (CDS)" as cds
' url of frcore is  [[https://interop.esante.gouv.fr/ig/fhir/cds]]

' artifact "Cahier De Liaison (CDL)" as cdl
' url of frcore is  [[https://interop.esante.gouv.fr/ig/fhir/cdl]]



archimate #Technology "Répertoire Offre Ressources en santé (ROR)" as ror <<technology-device>>
url of ror is  [[https://interop.esante.gouv.fr/ig/fhir/ror]]


ror --> frcore 
ror --> APIFHIRROR

artifact "Essais CLiniques Accessibles Interconnectés pour la Recherche ouverts à l'Ecosystème (ECLAIRE)" as eclaire 
url of eclaire is  [[https://interop.esante.gouv.fr/ig/fhir/eclaire]]


@enduml